### ISSUE TITLE
Fails on Android with `No such File or Directory`

### ISSUE THREAD

**Issue by timmolter** [char5742/flutter_silero_vad#4]
I freshly cloned the repo and ran it on an Android Phone with Android 12. Any ideas?

```
Exception has occurred.
PlatformException (PlatformException(AndroidAudioError, /data/user/0/com.example.flutter_silero_vad_example/cache/output.wav: open failed: ENOENT (No such file or directory), java.io.FileNotFoundException: /data/user/0/com.example.flutter_silero_vad_example/cache/output.wav: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1276)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1247)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1212)
	at xyz.luan.audioplayers.source.UrlSource.setForMediaPlayer(UrlSource.kt:16)
	at xyz.luan.audioplayers.player.MediaPlayerPlayer.setSource(MediaPlayerPlayer.kt:53)
	at xyz.luan.audioplayers.player.WrappedPlayer.setSource(WrappedPlayer.kt:29)
	at xyz.luan.audioplayers.AudioplayersPlugin.methodHandler(AudioplayersPlugin.kt:126)
	at xyz.luan.audioplayers.AudioplayersPlugin.access$methodHandler(AudioplayersPlugin.kt:29)
	at xyz.luan.audioplayers.AudioplayersPlugin$onAttachedToEngine$1$1.invoke(AudioplayersPlugin.kt:50)
	at xyz.luan.audioplayers.AudioplayersPlugin$onAttachedToEngine$1$1.invoke(AudioplayersPlugin.kt:50)
	at xyz.luan.audioplayers.AudioplayersPlugin$safeCall$1.invokeSuspend(AudioplayersPlugin.kt:75)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8611)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 20 more
, null))
```

**Comment by char5742** [comment]
Thank you for bringing this issue to our attention. Based on the details you've provided, it appears that the exception is caused by the app attempting to play the output.wav file before it has been generated. In our app, recording starts automatically on launch, and the Silero Vad feature saves the voice input to output.wav once it detects sound.

The error occurs because, if the Start button (for playback) is pressed before any sound is detected and recorded, the output.wav file does not exist yet, leading to a FileNotFoundException.

**Comment by timmolter** [comment]
OK. Now that I understand how it is supposed to work, I can confirm that the demo does indeed function properly. Thanks!
